name: Quasar Electron Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-capacitor:
    runs-on: ${{ matrix.os-versions }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os-versions: [windows-latest, macos-latest, ubuntu-latest]
        node-versions: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS Environment ${{ matrix.node-versions }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - run: yarn install && yarn global add @quasar/cli
      - run: yarn build:electron

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: release-${{ matrix.os-versions }}.zip
          path: './dist/electron/Packaged'

      - name: Create/Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: release-${{ matrix.os-versions }}.zip
          name: Release ${{ github.ref_name }}
          body: Automated Electron Build & Release
          draft: false
          prerelease: false
