name: Quasar Electron Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  username: puddingii
  email: gun4930@naver.com

jobs:
  auto-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog_output: ${{ steps.changelog-ci.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        id: changelog-ci
        with:
          config_file: changelog-ci-config.json
          release_version: ${{ github.ref_name }}
          github_token: ${{ secrets.GHCR_TOKEN }}
          committer_username: ${{ env.username }}
          committer_email: ${{ env.email }}

  release:
    runs-on: ${{ matrix.os-versions }}
    needs: [auto-changelog]

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os-versions: [windows-latest, macos-latest, ubuntu-latest]
        node-versions: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS Environment ${{ matrix.node-versions }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - run: yarn install && yarn global add @quasar/cli
      - run: yarn build:electron

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: release-${{ matrix.os-versions }}.zip
          directory: './dist/electron/Packaged'

      - name: Create/Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: ./dist/electron/Packaged/release-${{ matrix.os-versions }}.zip
          name: Release ${{ github.ref_name }}
          body: |
            Automated Electron Release & Change-log
            ${{ needs.auto-changelog.outputs.changelog_output }}
          draft: false
          prerelease: false
